image: "registry.gitlab.e.foundation/e/os/docker-android-apps-cicd:latest"

stages:
  - build

before_script:
  - export JAVA_HOME=/usr/lib/jvm/java-25-openjdk-amd64
  - export GRADLE_USER_HOME=$(pwd)/.gradle
  - chmod +x ./gradlew

cache:
  key: ${CI_PROJECT_ID}
  paths:
  - ./gradle/

build:
  stage: build
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - ./gradlew lint assemble
  artifacts:
    paths:
      - app/build/outputs/apk/
