image: "registry.gitlab.e.foundation/e/os/docker-android-apps-cicd:latest"

stages:
  - update-from-upstream
  - build
  - ai-review

include:
  - project: "e/templates"
    ref: main
    file: "/.gitlab/gitlab-ci/gitlab-ci-import-updates-from-upstream.yml"
  - project: "e/os/ai-review"
    ref: main
    file: "/.gitlab-ci.yml"

upstream_update:
  extends: .update-from-upstream
  variables:
    UPSTREAM_BRANCH: main
    LOCAL_BRANCH: develop

before_script:
  - export GRADLE_USER_HOME=$(pwd)/.gradle

build:
  stage: build
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH'
    - if: '$CI_COMMIT_TAG'
  cache:
    key: ${CI_PROJECT_ID}
    paths:
      - .gradle/
  script:
    - ./gradlew assembleRelease
  artifacts:
    paths:
      - app/build/outputs/apk

ai-review:
  needs:
    - job: build
      artifacts: true
