image: "registry.gitlab.e.foundation/e/os/docker-android-apps-cicd:latest"

stages:
  - update-from-upstream
  - build
  - publish
  - ai-review
  - code-quality

include:
  - project: "e/templates"
    ref: main
    file: "/.gitlab/gitlab-ci/gitlab-ci-import-updates-from-upstream.yml"
  - project: "e/templates"
    ref: main
    file: "/.gitlab/gitlab-ci/gitlab-ci-check-mr-description.yml"
  - project: "e/os/ai-review"
    ref: main
    file: "/.gitlab-ci.yml"

upstream_update:
  extends: .update-from-upstream
  variables:
    UPSTREAM_BRANCH: main
    LOCAL_BRANCH: develop

before_script:
  - export GRADLE_USER_HOME=$(pwd)/.gradle

.build_rules: &build_rules
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      variables:
        CACHE_POLICY: pull
      interruptible: true
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH || $CI_COMMIT_BRANCH =~ /^v/
      variables:
        CACHE_POLICY: pull-push
      interruptible: false
    - if: $CI_COMMIT_TAG
      variables:
        CACHE_POLICY: pull-push
      interruptible: false
    - when: never
  allow_failure: false
  cache:
    key: ${CI_PROJECT_ID}
    paths:
      - .gradle/
    policy: $CACHE_POLICY

build-release:
  <<: *build_rules
  stage: build
  script:
    - ./gradlew assembleRelease
  artifacts:
    paths:
      - app/build/outputs/apk/release

analysis:
  stage: code-quality
  <<: *build_rules
  needs:
    - build-release
  script:
    - ./gradlew detekt lintRelease
  artifacts:
    paths:
      - app/build/reports/
      - build/reports/

.rules_publish:
  rules: &rules_publish
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: manual
    - if: '$CI_COMMIT_TAG !~ "/^$/"'
      when: always

publish-companionapi:
  stage: publish
  needs:
    - job: build-release
  rules: *rules_publish
  script:
    - ./gradlew :companion-api:build
    - ./gradlew :companion-api:publish
  allow_failure: true
